### PR TITLE
Moved from go-dep to go mod

### PR DESCRIPTION
**Pull request by mugdha-adhav**
## Description
- Move from go dep to go mod
- Facing dependency issues as the deps were pinned to older versions
- Moving to go mod will help manage dependencies better and point to latest release at ease

## Testing Done
- Tested on Linux ubuntu 18.04
- Docker image for linux platform works fine

### CODE REVIEW

**Comment by mithilarun** [comment]
It's hard to look at the changes because of the number of files that are removed? Is `go.mod` the only file added? What other changes were made?

**Comment by mithilarun** [comment]
Also, how are we managing `go.mod`? Is that file generated automatically by `go mod init`?

**Comment by mugdha-adhav** [comment]
So for moving from go-dep to go mod, we have to remove the existing vendor directory which has all the dependencies stored in it. The vendor directory gets too large so the number of files deleted is huge.

Also for moving to go mod, it creates 2 files, go.mod and go.sum, where go.mod stores all your dependencies with their versions and the go.sum files stores the  cryptographic hashes of the deps

**Comment by mugdha-adhav** [comment]
> Also, how are we managing `go.mod`? Is that file generated automatically by `go mod init`?

Yes, `go mod init` command automatically created the go.mod and go.sum files from the existing Gopkg.toml

But addition to that, I have updated the dependencies in the go.mod to use latest versions of all the dependencies

**Comment by mugdha-adhav** [comment]
> It's hard to look at the changes because of the number of files that are removed? Is `go.mod` the only file added? What other changes were made?

As the deps are updated, there are a few implementation changes as well. But I have tested the changes thoroughly using `go test` and we have also written unit tests for most to the modules to ensure that the operator remains consistent.

**Review by mithilarun — APPROVED** [review]
/lgtm
/approve

**Review by tlindev — APPROVED** [review]

**Pull request merged**
