### PR TITLE
Add support for loki in the outputs CRD

### PR DESCRIPTION
**Pull request by mugdha-adhav**
## Description
- Add support in output CR for loki datastore. 
- The config created for fluentd needs to be modified to added loki parameters. 
- Add example for loki in templates

## Testing Done
Tested locally on minikube cluster

### CODE REVIEW

**Review by smanpathak — CHANGES_REQUESTED** [review]
Looks good,
please add a unit test for loki param function

**Comment by mayuresh108** [comment]
Tried deleting after installing pf9-log. fluentd deployment and fluent bit daemonsets were not deleted. Also the outputs object and its crd was not deleted.
Maybe we need to set the owner of these objects to the fluentd operator.

**Comment by mugdha-adhav** [comment]
> Tried deleting after installing pf9-log. fluentd deployment and fluent bit daemonsets were not deleted. Also the outputs object and its crd was not deleted.
> Maybe we need to set the owner of these objects to the fluentd operator.

Yes. We can raise a new PR for these changes

**Comment by mugdha-adhav** [comment]
> Looks good,
> please add a unit test for loki param function

Added tests for loki output params

**Pull request merged**
